### ISSUE TITLE
Проблемы запуска

### ISSUE THREAD

**Issue by nikitosalo** [ilink-pro/web#23]
Предусловие:
Стянул проект, запустил yarn, далее открыл докер, в контейнере identity вот такие ошибки и он не поднимается

error - Failed to load SWC binary for linux/x64, see more info here: https://nextjs.org/docs/messages/failed-loading-swc
info  - Attempted to load @next/swc-linux-x64-gnux32, but it was not installed
info  - Attempted to load @next/swc-linux-x64-musl, but it was not installed
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Attempted to load @next/swc-linux-x64-gnu, but it was not installed
info  - Attempted to load @next/swc-linux-x64-gnux32, but it was not installed
info  - Attempted to load @next/swc-linux-x64-musl, but it was not installed

**Comment by TFK70** [comment]
@nikitosalo у тебя ведь мак на М1?

**Comment by TorinAsakura** [comment]
@TFK70 нет, у него линукс, М1 у другого Никиты

**Comment by TFK70** [comment]
@nikitosalo дай пожалуйста скриншот бандлов в `.yarn/unplugged` которые с `@next` начинаются:

![Screenshot from 2022-05-24 18-45-01](https://user-images.githubusercontent.com/62806448/170050784-aa8598b4-0826-4625-8935-26416c068b40.png)

**Comment by TFK70** [comment]
@nikitosalo [Здесь](https://github.com/ilink-pro/web/pull/24) попробуй сделать `docker-compose up yarn` и `docker-compose up identity`

У тебя пакеты сбилдились под макось, а в докере нужны линуксовые
