### ISSUE TITLE
Изменения в структуре проекта

### ISSUE THREAD

**Issue by nikitosalo** [ilink-pro/web#33]
### Скоуп
Изменения в структуре проекта

### Описание
Обобщенное описание проблемы.
В последних изменениях исчезла папка site

Здесь же указывается контекст, при наличии
Текущая структура отличается от примеров из таски https://github.com/ilink-pro/web/issues/14

Также интересует, как именно мы создаем фрагменты?

### Вопрос
1) Хотел бы узнать, где именно нам создавать фрагменты?
2) Так же каким образом генерируется шаблон и есть ли это вообще, если нет, то что именно нужно сделать для создания фрагмента (копипаста другого фрагмента и его изменение или что-то иное)?

**Comment by TFK70** [comment]
@nikitosalo 

> В последних изменениях исчезла папка site

Да, просто скоуп был переименован в `dashboard`, а так все осталось прежним

> Текущая структура отличается от примеров из таски https://github.com/ilink-pro/web/issues/14

Различие только в том, где лежат фрагменты. Во всем остальном все осталось прежним. Основной целью было дать пример того, чем являются фрагменты. За более точечным примером фрагментов - заглянуть можно [сюда](https://github.com/torin-asakura/VSBLE/tree/master/site/fragments)

> Также интересует, как именно мы создаем фрагменты?

Немного не понял вопрос. Фрагменты представляют собой реакт-компоненты

> Хотел бы узнать, где именно нам создавать фрагменты?

Директория [fragments](https://github.com/ilink-pro/web/tree/master/dashboard/fragments). У каждого скоупа на проекте свой набор фрагментов. Конкретно сейчас работа ведется над скоупом `dashboard`, так что фрагменты относящиеся к дэшборду создаются в `dashboard/fragments`

> Так же каким образом генерируется шаблон и есть ли это вообще, если нет, то что именно нужно сделать для создания фрагмента (копипаста другого фрагмента и его изменение или что-то иное)?

Тоже немного не понял какой шаблон здесь подразумевается. Реализация фрагментов почти на 100% зависит от проекта, так что писать генератор фрагментов ради того чтобы генерировать 10 строк - не очень здравая мысль.

Шаблоны в целом довольно удобная вещь, их можно [создавать в своей IDE](https://www.jetbrains.com/help/idea/using-file-and-code-templates.html#syntax). Работают примерно следующим образом:

https://user-images.githubusercontent.com/62806448/148673762-23f12b97-621a-4240-8eb1-1738587f6b68.mov

Вот src шаблонов из видео (для примера):

<details>

`${NAME}.component` (`.tsx`)

<details>

```javascript
#set( $CCNAME = ${StringUtils.removeAndHump($NAME, '-')} )
#set( $INTERFACE = ${CCNAME} + 'Props' )

import React  from 'react'
import { FC } from 'react'

import { ${INTERFACE} } from './${NAME}.interface'

const ${CCNAME}: FC<${INTERFACE}> = () => {
   return ()
}

export { ${CCNAME} }
```

</details>

`${NAME}.styles` (`.ts`)

<details>

```javascript
import { styleFn } from 'styled-system'
import { CSSObject } from '@emotion/css'

export const baseStyles = {}    
```

</details>

`${NAME}.interface` (`.ts`)

<details>

```javascript
#set( $CCNAME = ${StringUtils.removeAndHump($NAME, '-')} )

export interface ${CCNAME}Props {}
```

</details>

`index` (`.ts`)

<details>

```javascript
export * from './${NAME}.component'
export * from './${NAME}.interface'
```

</details>

</details>

**Comment by nikitosalo** [comment]
@TFK70 гуд, спасибо, единственное, тут package.json у каждого фрагмента свой, его мы также таскаем по директориям фрагментов, дополняя зависимостями из ui?

**Comment by TorinAsakura** [comment]
@nikitosalo Почитай пожалуйста про yarn workspace, что это, для чего юзается, тогда станет понятно.
